# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpparma_hello_world <- function() {
    .Call(`_rfpar_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_rfpar_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_rfpar_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_rfpar_rcpparma_bothproducts`, x)
}

set_seed_cpp <- function(seed) {
    invisible(.Call(`_rfpar_set_seed_cpp`, seed))
}

find_midpoints_cpp <- function(x) {
    .Call(`_rfpar_find_midpoints_cpp`, x)
}

decision_cpp <- function(tree, node, observation) {
    .Call(`_rfpar_decision_cpp`, tree, node, observation)
}

calculate_mse_cpp <- function(x) {
    .Call(`_rfpar_calculate_mse_cpp`, x)
}

make_reg_decision_rule_cpp <- function(ss, bag_out, bag_feat, n_feats, seed, min_node_size) {
    .Call(`_rfpar_make_reg_decision_rule_cpp`, ss, bag_out, bag_feat, n_feats, seed, min_node_size)
}

build_reg_nodes_cpp <- function(tree_data, sample_set_data, node_i, outcome_data, feats_data, n_feats_to_consider, mns, seed, isCh1) {
    invisible(.Call(`_rfpar_build_reg_nodes_cpp`, tree_data, sample_set_data, node_i, outcome_data, feats_data, n_feats_to_consider, mns, seed, isCh1))
}

generate_reg_tree_cpp <- function(bagged_outcome, bagged_feats, n_feats, min_node_size, setseed) {
    .Call(`_rfpar_generate_reg_tree_cpp`, bagged_outcome, bagged_feats, n_feats, min_node_size, setseed)
}

predict_reg_cpp <- function(forest, train) {
    .Call(`_rfpar_predict_reg_cpp`, forest, train)
}

calculate_gini_cpp <- function(x) {
    .Call(`_rfpar_calculate_gini_cpp`, x)
}

numeric_mode_cpp <- function(x) {
    .Call(`_rfpar_numeric_mode_cpp`, x)
}

make_class_decision_rule_cpp <- function(ss, bag_out, bag_feat, n_feats, seed, min_node_size) {
    .Call(`_rfpar_make_class_decision_rule_cpp`, ss, bag_out, bag_feat, n_feats, seed, min_node_size)
}

build_class_nodes_cpp <- function(tree_data, sample_set_data, node_i, outcome_data, feats_data, n_feats_to_consider, mns, seed, isCh1) {
    invisible(.Call(`_rfpar_build_class_nodes_cpp`, tree_data, sample_set_data, node_i, outcome_data, feats_data, n_feats_to_consider, mns, seed, isCh1))
}

generate_class_tree_cpp <- function(bagged_outcome, bagged_feats, n_feats, min_node_size, setseed) {
    .Call(`_rfpar_generate_class_tree_cpp`, bagged_outcome, bagged_feats, n_feats, min_node_size, setseed)
}

generate_class_forest_cpp <- function(outcome, features, mtry, ntrees, min_node_size, setseed) {
    .Call(`_rfpar_generate_class_forest_cpp`, outcome, features, mtry, ntrees, min_node_size, setseed)
}

predict_class_cpp <- function(forest, train) {
    .Call(`_rfpar_predict_class_cpp`, forest, train)
}

